<template>
  <div style="display: none"></div>
</template>

<script>
export default {
  data() {
    return {
      name: "Mountains",
      mountainCards: [
        {
          title: "Diamond Head",
          height: 232,
          feet: 761,
          range: "Hawaii",
          country: "United States",
          ascent: "Unknown",
          content:
            "The unique profile of Diamond Head (Lē‘ahi) sits prominently near the eastern edge of Waikiki’s coastline. Hawaii’s most recognized landmark is known for its historic hiking trail, stunning coastal views, and military history.",
          imageSrc: "src/assets/Mountains/Images/diamond-head.jpg",
          imageAlt: "Diamond Head",
        },
        {
          title: "Suur Munamagi",
          height: 318,
          feet: 1043,
          range: "Haanja",
          country: "Estonia",
          ascent: "Unknown",
          content:
            "Translated to Great Egg Mountain is the highest peak in Estonia.",
          imageSrc: "src/assets/Mountains/Images/Suur_Munamagi.jpg",
          imageAlt: "Surr MunaMägi",
        },
        {
          title: "Great Mell Fell",
          height: 537,
          feet: 1762,
          range: "Lake District",
          country: "England",
          ascent: "Unknown",
          content:
            "An isolated hill which rises abruptly from a wide expanse of marshy lowland to a height of 537 m. The fell has smooth, rounded outlines with no crags. ",
          imageSrc: "src/assets/Mountains/Images/Greatmellfell.jpg",
          imageAlt: "Great Mell Fell",
        },
        {
          title: "Qalorujoorneq",
          height: 676,
          feet: 2218,
          range: "Greenland",
          country: "Denmark",
          ascent: "Unknown",
          content: "Qalorujoorneq is the highest peak in Greenland.",
          imageSrc: "src/assets/Mountains/Images/Saajat.jpg",
          imageAlt: "Qalorujoorneq",
        },

        {
          title: "Table Mountain",
          height: 1085,
          feet: 3558,
          range: "Cape Peninsula",
          country: "South Africa",
          ascent: "Unknown",
          content:
            "Table Mountain is a flat-topped mountain forming a prominent landmark overlooking the city of Cape Town.",
          imageSrc: "src/assets/Mountains/Images/tableMountain.webp",
          imageAlt: "Table Mountain",
        },
        {
          title: "Mount Hombori",
          height: 1155,
          feet: 3786,
          range: "Hombori Mountains",
          country: "Mali",
          ascent: "Unknown",
          content: "Highest point in Mali. It is a sandstone plateau.",
          imageSrc: "src/assets/Mountains/Images/hombori.jpg",
          imageAlt: "Mount Hombori",
        },
        {
          title: "Ben Nevis",
          height: 1345,
          feet: 4413,
          range: "None",
          country: "Scotland",
          ascent: "1771",
          content: "Highest peak in Scotland, UK and British Isles",
          imageSrc: "src/assets/Mountains/Images/bennevis.jpg",
          imageAlt: "Ben Nevis",
        },
        {
          title: "Snæfellsjökull",
          height: 1446,
          feet: 4744,
          range: "None",
          country: "Iceland",
          ascent: "Unknown",
          content:
            "It is a glacier-covered stratovanocano in western Iceland. ",
          imageSrc: "src/assets/Mountains/Images/Snaefellsjokull.jpg",
          imageAlt: "Snæfellsjökull",
        },
        {
          title: "Sněžka",
          height: 1602,
          feet: 5259,
          range: "Giant Mountains",
          country: "Czech Republic / Poland",
          ascent: "Unknown",
          content:
            "The highest point in the Czech Republic. Borders with Poland.",
          imageSrc: "src/assets/Mountains/Images/snezka.webp",
          imageAlt: "Snezka",
        },
        {
          title: "Mount Washington",
          height: 1917,
          feet: 5259,
          range: "Presidental Range",
          country: "USA",
          ascent: "1642",
          content:
            "The mountain is notorious for its erratic weather. The highest recorded wind speed at the summit was 372 kmh the highest wind speed not associated with tornado or cyclone.",
          imageSrc: "src/assets/Mountains/Images/washington.jpg",
          imageAlt: "Mount Washington",
        },
        {
          title: "Mount Bogong",
          height: 1986,
          feet: 6516,
          range: "Victorian Alps",
          country: "Australia",
          ascent: "1854",
          content:
            "Highest mountain in Victoria, Australia. It is part of the Australian Alps National Park. ",
          imageSrc: "src/assets/Mountains/Images/bogong.jpg",
          imageAlt: "Mount Bogong",
        },
        {
          title: "Polar Bear Peak",
          height: 2016,
          feet: 6614,
          range: "Chugach Mountains",
          country: "USA",
          ascent: "1966",
          content:
            "The peak was named in 1963 by members of the Mountaineering Club of Alaska because snow patch on its north face resembles a Polar bear skin.",
          imageSrc: "src/assets/Mountains/Images/Polar_Bear_Peak.jpg",
          imageAlt: "Polar Bear Peak",
        },
        {
          title: "Mount Kosciuszko",
          height: 2228,
          feet: 7310,
          range: "Main Range",
          country: "Australia",
          ascent: "Unknown",
          content:
            "Tallest mountain in Australia and one of the seven summits.",
          imageSrc: "src/assets/Mountains/Images/mount-kosciuszko.jpg",
          imageAlt: "Mount Kosciuszko",
        },
        {
          title: "Špik",
          height: 2472,
          feet: 8110,
          range: "Julian Alps",
          country: "Slovenia",
          ascent: "1778",
          content:
            'Špik is a mountain in the Slovenian Julian Alps. The mountain\'s name is a cognate of the English "spike," derived from its pointed shape.',
          imageSrc: "src/assets/Mountains/Images/spik.jpg",
          imageAlt: "Spik",
        },
        {
          title: "Barbeau Peak",
          height: 2616,
          feet: 8583,
          range: "Ellesmere Island",
          country: "Canada",
          ascent: "1967",
          content:
            "The mountain was named in 1969 after Marius Barbeau, a Canadian anthropologist whose research into First Nations and Inuit cultures gained him international acclaim.",
          imageSrc: "src/assets/Mountains/Images/Barbeau_Peak.jpg",
          imageAlt: "Barbeau Peak",
        },
        {
          title: "Triglav",
          height: 2864,
          feet: 8583,
          range: "Julian Alps",
          country: "Slovenia",
          ascent: "18",
          content:
            "The highest mountain in Slovenia and the highest peak of the Julian Alps. The mountain is the pre-eminent symbol of the Slovene nation, appearing on the coat of arms and flag of Slovenia. ",
          imageSrc: "src/assets/Mountains/Images/triglav.jpg",
          imageAlt: "Triglav",
        },
        {
          title: "Mount Olympus",
          height: 2917,
          feet: 9570,
          range: "Olympus Range",
          country: "Greece",
          ascent: "400BC/1913 - Modern Ascent",
          content:
            "In Greek mythology, Olympus is the home of the Greek gods, on Mytikas peak. The mountain has exceptional biodiversity and rich flora.",
          imageSrc: "src/assets/Mountains/Images/olympus.jpg",
          imageAlt: "",
        },

        {
          title: "Glacier Peak",
          height: 3213,
          feet: 10541,
          range: "Cascades",
          country: "United States",
          ascent: "1898",
          content:
            "Also known as Dakobed or Takobia it is the most isolated of the five major stratovolcanoes of the Cascade Volcanic Arc in the U.S state of Washington.  ",
          imageSrc: "src/assets/Mountains/Images/glacier_peak.jpg",
          imageAlt: "Glacier Peak",
        },
        {
          title: "Piz Badile",
          height: 3308,
          feet: 10853,
          range: "Bregaglia",
          country: "Switzerland/Italy",
          ascent: "1867",
          content:
            "Its north-face overlooking the Swiss Alps is considered one of the six great north faces of the Alps.",
          imageSrc: "src/assets/Mountains/Images/Badile.jpg",
          imageAlt: "Piz Badile",
        },
        {
          title: "Semeru",
          height: 3676,
          feet: 12066,
          range: "None",
          country: "Indonesia",
          ascent: "Unknown",
          content:
            'The name Semeru is derived from Meru, the central world mountain in Hinduism, or Sumeru, the abode of gods. This stratovolcano is Mahameru, meaning "The Great Mountain" in Sanskrit.',
          imageSrc: "src/assets/Mountains/Images/semeru.jpg",
          imageAlt: "Semeru",
        },
        {
          title: "Aoraki / Mount Cook",
          height: 3754,
          feet: 12317,
          range: "Southern Alps",
          country: "New Zealand",
          ascent: "1894",
          content:
            "Aoraki / Mount Cook consists of three summits: from south to north, the Low Peak (3,593 m or 11,788 ft), the Middle Peak (3,717 m or 12,195 ft) and the High Peak.",
          imageSrc: "src/assets/Mountains/Images/aoraki.webp",
          imageAlt: "Aoraki / Mount Cook",
        },
        {
          title: "Mount Fuji",
          height: 3776,
          feet: 12388,
          range: "None",
          country: "Japan",
          ascent: "663",
          content:
            'Is an active stratovolcano  It is one of the Japan\'s  "Three Holy Mountains " and the tallest mountain in Japan. It is often depicted in art and photography.',
          imageSrc: "src/assets/Mountains/Images/fuji.jpg",
          imageAlt: "Mount Fuji",
        },
        {
          title: "Eiger",
          height: 3967,
          feet: 13015,
          range: "Bernese Alps",
          country: "Switzerland",
          ascent: "1858",
          content:
            "The most notable feature of Eiger is its nearly 1800 metre high north face of rock and ice named Eiger-Nordwand, Eigerwand or just Nordwand, which is the biggest north face in the Alps.",
          imageSrc: "src/assets/Mountains/Images/eiger.jpeg",
          imageAlt: "Eiger",
        },
        {
          title: "Mount Kinabalu",
          height: 4095,
          feet: 13435,
          range: "Crocker Mountains",
          country: "Malaysia",
          ascent: "1851",
          content:
            "The mountain and its surroundings are among the most important biological sites in the world.",
          imageSrc: "src/assets/Mountains/Images/kinabalu.webp",
          imageAlt: "Mount Kinabalu",
        },
        {
          title: "Phoenix Peak",
          height: 4237,
          feet: 13901,
          range: "Kenat Mountains",
          country: "Canada",
          ascent: "1964",
          content:
            " The peak was named in 1965 by the Mountaineering Club of Alaska for the first ship ever built in Russian America, the Phoenix, which was constructed in 1794 by Russians in nearby Resurrection Bay.",
          imageSrc: "src/assets/Mountains/Images/Phoenix_Peak.jpg",
          imageAlt: "Phoenix Peak",
        },

        {
          title: "Mount Rainier",
          height: 4392,
          feet: 14411,
          range: "Cascade Range",
          country: "USA",
          ascent: "1870",
          content:
            "A large active stratovolcano in the Cascade Range of the Pacific Northwest in the United States.",
          imageSrc: "src/assets/Mountains/Images/Phoenix_Peak.jpg",
          imageAlt: "Mount Rainier",
        },

        {
          title: "Matterhorn",
          height: 4478,
          feet: 14692,
          range: "Pennine Alps",
          country: "Switzerland / Italy",
          ascent: "1865",
          content:
            "Translated to Peak of Meadows. Matterhorn has a pyramidal shape nearly all four faces face compass points. It is one of the most famous north faces.",
          imageSrc: "src/assets/Mountains/Images/matterhorn.jpg",
          imageAlt: "Matterhorn",
        },
        {
          title: "Mont Blanc",
          height: 4748,
          feet: 15582,
          range: "Mont Blanc Massif",
          country: "France / Italy",
          ascent: "1786",
          content:
            "It is the highest peak in the Alps and Europe. It is the second most prominent mountain in Europe. It gives its name to the Mont Blanc massif, which straddles parts of France, Italy and Switzerland. ",
          imageSrc: "src/assets/Mountains/Images/mont_blanc.jpg",
          imageAlt: "Mont Blanc",
        },
        {
          title: "Vinson Massif",
          height: 4892,
          feet: 16050,
          range: "Sentinel Range",
          country: "Antartica",
          ascent: "1966",
          content:
            "Highest peak in Antarctica and one of the seven summits. It lies within the Sentinel Range of the Ellsworth Mountains. ",
          imageSrc: "src/assets/Mountains/Images/vinson.jpg",
          imageAlt: "Mount Vinson",
        },
        {
          title: "Pico Bolivar",
          height: 4981,
          feet: 16345,
          range: "Cordillera de Mérida",
          country: "Venezuela",
          ascent: "1935",
          content:
            "The highest mountain in Venezuela. The peak is named after the Venezuelan independence hero Simón Bolívar.",
          imageSrc: "src/assets/Mountains/Images/bolivar.jpg",
          imageAlt: "Pico Bolivar",
        },

        {
          title: "Vinicunca",
          height: 5200,
          feet: 17060,
          range: "Andes",
          country: "Peru",
          ascent: "Unknown",
          content:
            "According to the Cultural Landscape Office of the Decentralization of the City of Cusco, the seven colors of the mountain are due to its mineralogical composition.",
          imageSrc: "src/assets/Mountains/Images/vinicunca.jpg",
          imageAlt: "Vinicunca",
        },
        {
          title: "Popocatepetl",
          height: 5426,
          feet: 17783,
          range: "Trans-Mexican Volcanic Belt",
          country: "Mexico",
          ascent: "1519",
          content:
            "an active stratovolcano located in the states of Puebla, Morelos, and Mexico in central Mexico. It lies in the eastern half of the Trans-Mexican volcanic belt. It is the second highest peak in Mexico.",
          imageSrc: "src/assets/Mountains/Images/popocatepetl.jpg",
          imageAlt: "Popocatepetl",
        },
        {
          title: "Mount Elbrus",
          height: 5642,
          feet: 18510,
          range: "Caucasus Mountains",
          country: "Russia",
          ascent: "1829",
          content:
            "Highest peak in Russia and in Europe. It is the highest stratovolcano in Eurasia. It has two summits.",
          imageSrc: "src/assets/Mountains/Images/elbrus.jpg",
          imageAlt: "Mount Elbrus",
        },
        {
          title: "Mount Kilimanjaro",
          height: 5895,
          feet: 19341,
          range: "None",
          country: "Tanzania",
          ascent: "1889",
          content:
            "Mt. Kilimanjaro is a dormant volcano. It is the highest peak in Africa and the highest single free standing mountain above sea level in the world.",
          imageSrc: "src/assets/Mountains/Images/kilimanjaro.jpg",
          imageAlt: "Mount Kilimanjaro",
        },
        {
          title: "Huayna Potosi",
          height: 6088,
          feet: 19974,
          range: "Cordillera Blanca, Andes",
          country: "Bolivia",
          ascent: "1919",
          content:
            "Located near El Alto and La Paz is the most popular climb in Bolivia.",
          imageSrc: "src/assets/Mountains/Images/potosi.jpg",
          imageAlt: "Huayna Potosi",
        },
        {
          title: "Mount Denali",
          height: 6190,
          feet: 20194,
          range: "Alaska Range",
          country: "USA",
          ascent: "1913",
          content:
            "Is the highest peak in the North America and one of the seven summits. It is the tallest mountain in the world from base to peak on land (5500m). During a winter temperatures can get low as -50 degrees.",
          imageSrc: "src/assets/Mountains/Images/denali.webp",
          imageAlt: "Mount Denali",
        },
        {
          title: "Huandoy",
          height: 6395,
          feet: 20977,
          range: "Cordillera Blanca, Andes",
          country: "Peru",
          ascent: "1932",
          content:
            "It is a snow capped mountain with four peaks and the second highest peak in Cordillera Blanca",
          imageSrc: "src/assets/Mountains/Images/huandoy.jpg",
          imageAlt: "Uandoy",
        },
        {
          title: "Mount Kailash",
          height: 6638,
          feet: 21778,
          range: "None",
          country: "Tibet (China)",
          ascent: "Unclimbed",
          content:
            "Mount Kailash is a sacred mountain in Hinduism, Buddhism, Jainism and Bon religion. People undertake pilgrimage to the mountain. Because of this it is prohibited to climb the mountain.",
          imageSrc: "src/assets/Mountains/Images/kailash.jpg",
          imageAlt: "Mount Kailash",
        },
        {
          title: "Aconcagua",
          height: 6961,
          feet: 22837,
          range: "Andes",
          country: "Argentina",
          ascent: "1897",
          content:
            "It is the highest mountain in the Americas and highest outside of the Asia.",
          imageSrc: "src/assets/Mountains/Images/aconcagua.jpg",
          imageAlt: "Aconcagua",
        },
        {
          title: "Machapuchare",
          height: 6993,
          feet: 22943,
          range: "Annapurna Himalayas",
          country: "Nepal",
          ascent: "Unclimbed",
          content:
            "Is a mountain situated in the Annapurna massif. Its highest peak has never been officially climbed due to being prohibited by the Nepali government.",
          imageSrc: "src/assets/Mountains/Images/machapuchare.jpg",
          imageAlt: "Machapuchare",
        },
        {
          title: "Lenin Peak",
          height: 7134,
          feet: 23406,
          range: "Pamir Mountains",
          country: "Tajikistan / Kyrgyzstan",
          ascent: "1928",
          content:
            "Originally it was named Mount Kaufmann after first Governor-General of the Russian Turkestan but it was later renamed after Soviet Union first leader.",
          imageSrc: "src/assets/Mountains/Images/lenin_peak.webp",
          imageAlt: "Lenin Peak",
        },
        {
          title: "Muztagh Tower",
          height: 7273,
          feet: 23862,
          range: "Karakoram Range",
          country: "Pakistan",
          ascent: "1956",
          content:
            " It straddles the border of the Gilgit–Baltistan region of Pakistan and the Xinjiang Uyghur Autonomous Region of China. Muztagh Tower is located between the basins of the Baltoro and Sarpo Laggo glaciers.",
          imageSrc: "src/assets/Mountains/Images/tower.jpg",
          imageAlt: "Muztagh Tower",
        },
        {
          title: "Gangkhar Puensum",
          height: 7570,
          feet: 24836,
          range: "Kurichu Range",
          country: "Bhutan",
          ascent: "Unclimbed",
          content:
            "It is the highest unclimbed mountain in the world. In Dzongkha language its name means White Peak of the Three Spiritual Brothers. In Bhutan all mountaineering is banned.",
          imageSrc: "src/assets/Mountains/Images/gangkhar.webp",
          imageAlt: "Gangkhar Peunsum",
        },
        {
          title: "Nanda Devi",
          height: 7816,
          feet: 25643,
          range: "Garhwal Himalayas",
          country: "India",
          ascent: "1936",
          content:
            'For a time it was consider the highest mountain in the world. The peakk whose name means "Bliss Giving Goddess" is regarded as the patron goddess of the Garhwall and Kumaon Himalayas.',
          imageSrc: "src/assets/Mountains/Images/nanda_devi.webp",
          imageAlt: "Nanda Devi",
        },
        {
          title: "Lhotse",
          height: 8516,
          feet: 27940,
          range: "Mahalangur Himalayas",
          country: "Nepal / China",
          ascent: "1956",
          content:
            "With Everest to the north and Nuptse to the west, Lhotse forms the apex of the massive horseshoe-shaped arc of the Everest massif. It is the least prominent of the eight-thousanders.",
          imageSrc: "src/assets/Mountains/Images/lhotse.jpg",
          imageAlt: "Lhotse",
        },
        {
          title: "Kangchenjunga",
          height: 8586,
          feet: 28169,
          range: "Kangchenjunga Himalayas",
          country: "Nepal / India",
          ascent: "1955",
          content:
            "Kangchenjunga is the third highest mountain in the world. It is located on the border between Nepal and the Indian state of Sikkim. ",
          imageSrc: "src/assets/Mountains/Images/kangchenjunga.jpg",
          imageAlt: "Kangchenjunga",
        },
        {
          title: "Cho Oyu",
          height: 8188,
          feet: 26864,
          range: "Mahalangur Himalayas",
          country: "Nepal / China",
          ascent: "1954",
          content:
            "Sixth highest mountain in the world. The mountain is the westernmost major peak of the Khumbu sub-section of the Mahalangur Himalaya 20 km west of Mount Everest.",
          imageSrc: "src/assets/Mountains/Images/cho-oyu.jpg",
          imageAlt: "Cho Oyu",
        },
        {
          title: "Manaslu",
          height: 8163,
          feet: 26781,
          range: "Manaslu Himalayas",
          country: "Nepal",
          ascent: "1956",
          content:
            "Manaslu is the eighth highest mountain in the world. It is located in the Mansiri Himal, part of the Nepalese Himalayas, in the west-central part of Nepal.",
          imageSrc: "src/assets/Mountains/Images/manaslu.jpg",
          imageAlt: "Manaslu",
        },
        {
          title: "Gasherbrum I",
          height: 8080,
          feet: 26509,
          range: "Karakoram Range",
          country: "Pakistan / China",
          ascent: "1958",
          content:
            "Gasherbrum I is the 11th highest mountain in the world. It is one of the Gasherbrum Peaks, located in the Karakoram Range of the Himalayas.",
          imageSrc: "src/assets/Mountains/Images/Gasherbrum.jpg",
          imageAlt: "Gasherbrum I",
        },
        {
          title: "Broad Peak",
          height: 8051,
          feet: 26414,
          range: "Karakoram Range",
          country: "Pakistan / China",
          ascent: "1957",
          content:
            "Broad Peak is the 12th highest mountain in the world. It is located in the Karakoram mountain range in Pakistan.",
          imageSrc: "src/assets/Mountains/Images/broad_peak.jpg",
          imageAlt: "Broad Peak",
        },

        {
          title: "Gasherbrum II",
          height: 8035,
          feet: 26362,
          range: "Karakoram Range",
          country: "Pakistan / China",
          ascent: "1956",
          content:
            "Gasherbrum II is the 13th highest mountain in the world. It is one of the Gasherbrum Peaks, located in the Karakoram Range of the Himalayas.",
          imageSrc: "src/assets/Mountains/Images/Gasherbrum_II.jpg",
          imageAlt: "Gasherbrum II",
        },

        {
          title: "Nanga Parbat",
          height: 8126,
          feet: 26660,
          range: "Himalayas",
          country: "Pakistan",
          ascent: "1953",
          content:
            "Nanga Parbat is the ninth highest mountain in the world. It is the western anchor of the Himalayas around which the Indus river skirts before it debouches into the plains of Pakistan.",
          imageSrc: "src/assets/Mountains/Images/Nanga-Parbat.webp",
          imageAlt: "Nanga Parbat",
        },
        {
          title: "Shishapangma",
          height: 8027,
          feet: 26246,
          range: "Jugal Himalayas",
          country: "China",
          ascent: "1964",
          content:
            "The only eight-thousander entirely within Chinese territory. It is the 14th highest mountain in the world and the lowest of the eight-thousanders.",
          imageSrc: "src/assets/Mountains/Images/shishapangma.jpg",
          imageAlt: "Shishapangma",
        },
        {
          title: "Annapurna I",
          height: 8091,
          feet: 26545,
          range: "Annapurna Himalayas",
          country: "Nepal",
          ascent: "1950",
          content:
            "Named after a Hindu goddess of food and nourishment, who is said to reside there. Name derives from Sanskrit meaning 'everlasting food'.",
          imageSrc: "src/assets/Mountains/Images/annapurna.webp",
          imageAlt: "Annapurna I",
        },
        {
          title: "K2",
          height: 8611,
          feet: 28251,
          range: "Karakoram Range",
          country: "Pakistan / China",
          ascent: "1954",
          content:
            "Known as Savage Mountain by George Bell K2 is second highest mountain and by some metrics the deadliest.",
          imageSrc: "src/assets/Mountains/Images/k2.jpg",
          imageAlt: "K2 Mountain",
        },
        {
          title: "Mount Everest",
          height: 8848,
          feet: 29029,
          range: "Mahalangur Himalayas",
          country: "Nepal / China",
          ascent: "1953",
          content:
            "Highest mountain above sea level. Everest's Nepali/Sanskrit name is Sagarmāthā meaning goddess of the sky.",
          imageSrc: "src/assets/Mountains/Images/everest.webp",
          imageAlt: "Mount Everest",
        },
        {
          title: "Dhaulagiri",
          height: 8167,
          feet: 26795,
          range: "Dhaulagiri Himalayas",
          country: "Nepal",
          ascent: "1960",
          content:
            "Seventh highest mountain in the world and the highest mountain within the borders of a single country. Dhaulagiri means dazzlig, white, beautiful (Sanskrit).",
          imageSrc: "src/assets/Mountains/Images/dhaulagiri.jpg",
          imageAlt: "Dhaulagiri",
        },
        {
          title: "Makalu",
          height: 8463,
          feet: 27766,
          range: "Mahalangur Himalayas",
          country: "Nepal / China",
          ascent: "1955",
          content:
            "Fifth highest mountain on Earth. It is an isolated peak shaped as a four-sided pyramid. It is located 19km (12mi) from Mount Everest",
          imageSrc: "src/assets/Mountains/Images/makalu.avif",
          imageAlt: "Makalu",
        },
      ],
    };
  },
  computed: {
    mountainCards() {
      return this.mountainCards;
    },
  },
};
</script>
